title: Docker Docs
baseURL: https://docs.docker.com/
refLinksErrorLevel: WARNING
enableGitInfo: true
tableOfContents:
  startLevel: 2
  endLevel: 4

params:
  analytics:
    google: GTM-WL2QLG5
    onetrust: 8e0ebfd9-035d-4ec2-9b2f-a2de9c09f906
    hotjar: 3169877
  algolia_appid: 3XRLW0LZH9
  algolia_apikey: 2899036ce47dba191b8dc1758e4bc6a4
  versions:
    latest_engine_api_version: "1.41"
    docker_ce_version: "20.10"
    compose_v1_version: "1.29.2"
    compose_version: "v2.13.0"
    compose_file_v3: "3.9"
    compose_file_v2: "2.4"
    machine_version: "0.16.0"
    distribution_version: "2.7"
    compose_switch_version: "1.0.4"
    buildkit_version: "0.10.5"
    min_api_threshold: 1.40

markup:
  goldmark:
    extensions:
      typographer: false
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    noClasses: false

related:
  includeNewer: true
  indices:
    - name: topics
      weight: 100
    - name: keywords
      weight: 40
  threshold: 80
  toLower: false

module:
  imports:
    - path: github.com/moby/moby
      mounts:
        - source: docs/api
          target: content/engine/api
          includeFiles: "**.md"
        - source: docs/api
          target: static/reference/engine
          includeFiles: "*.yaml"
    - path: github.com/moby/buildkit
      mounts:
        - source: frontend/dockerfile/docs/reference.md
          target: content/engine/reference/builder.md
        - source: docs/buildkitd.toml.md
          target: content/build/buildkit/toml-configuration.md
        - source: docs/attestations/slsa-definitions.md
          target: content/build/attestations/slsa-definitions.md
        - source: docs/attestations/attestation-storage.md
          target: content/build/attestations/attestation-storage.md
    # - path: github.com/docker/cli/docs
    #   mounts:
    #     - source: extend
    #       target: content/engine/extend
    #     - source: deprecated.md
    #       target: content/engine/deprecated.md
    #     - source: reference/run.md
    #       target: content/engine/run-reference.md
    #     - source: reference/commandline/cli.md
    #       target: content/reference/cli/cli.md
    #     - source: reference/commandline/dockerd.md
    #       target: content/reference/cli/dockerd.md


outputFormats:
  redirects:
    baseName: redirects
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true

outputs:
  home:
    - html
    - redirects
  term:
    - html
    - json

taxonomies:
  topic: topics

languages:
  en:
    languageName: English
